### ISSUE TITLE
A license header is shown in the INFO message box of logging

### ISSUE THREAD

**Issue by kasunbg** [wso2/carbon-commons#273]
See the attached screenshot. The info box is shown we change the logging level of any logger.

<img width="891" alt="screen shot 2017-06-21 at 4 48 21 pm" src="https://user-images.githubusercontent.com/936037/27381748-9e2c406e-56a1-11e7-8f0a-dacf839a8147.png">

**Comment by jsdjayanga** [comment]
Fixed with https://github.com/wso2/carbon-commons/commit/867fbb4249675a7ddeb7865beb290f48c2196054
