### ISSUE TITLE
Upgrade httpclient dependency version

### ISSUE THREAD

**Issue by nuwandiw** [wso2/carbon-commons#288]
**Description:**
carbon-commons repo is using an old orbit version of httpclient

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by jsdjayanga** [comment]
Lib was updated to 4.3.6.wso2v1
